apiVersion: v1
kind: ReplicationController
metadata:
  name: arangodb
  labels:
    name: arangodb
spec:
  replicas: 1
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    name: arangodb
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: arangodb
    spec:
      replicas: 1
      containers:
      - image: arangodb/arangodb:latest
        name: arangodb
        ports:
        - containerPort: 8529
          name: arangodb
        volumeMounts:
        - name: arangodb-persistent-storage
          mountPath: /var/lib/arangodb
      volumes:
      - name: arangodb-persistent-storage
        gcePersistentDisk:
          pdName: arangodb-disk
          fsType: ext4
