apiVersion: v1
kind: Service
metadata:
  labels:
    name: sgbd
  name: sgbd
spec:
  type: LoadBalancer
  ports:
    - port: 8529
      targetPort: 8529
      protocol: TCP
  selector:
    name: arangodb
