apiVersion: v1
kind: Pod
metadata:
  name: spring
  labels:
    name: spring
spec:
  containers:
  - image: eu.gcr.io/mbzenika/spring:latest
    name: spring
    ports:
    - containerPort: 8080
      name: spring
    env:
    - name: SGBD_USER
      value: zenika
    - name: SGBD_PASSWORD
      value: zenika
    - name: OAUTH_CLIENT
      value: 1083777438685-kjrgndua0oiqhlhpl67qdjvjqn4okkoo.apps.googleusercontent.com
    - name: OAUTH_SECRET
      value: 6DsmY0wP6wWzXMGf54ymzkRv
