apiVersion: v1
kind: ReplicationController
metadata:
  name: spring
  labels:
    name: spring
spec:
  replicas: 1
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    name: spring
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: spring
    spec:
      containers:
      - image: eu.gcr.io/mbzenika/spring:latest
        name: spring
        ports:
        - containerPort: 8080
          name: spring
        env:
        - name: SGBD_USER
          value: zenika
        - name: SGBD_PASSWORD
          value: zenika
        - name: OAUTH_CLIENT
          value: 1083777438685-kjrgndua0oiqhlhpl67qdjvjqn4okkoo.apps.googleusercontent.com
        - name: OAUTH_SECRET
          value: 6DsmY0wP6wWzXMGf54ymzkRv
