var keyMirror = require("react/lib/keyMirror");

module.exports = keyMirror({
  LOAD_PROJECTS_SUCCESS: null,
  LOAD_PROJECTS_FAIL: null,

  LOAD_NEXT_PROJECTS_SUCCESS: null,
  LOAD_NEXT_PROJECTS_FAIL: null,

  LOAD_PROJECT_SUCCESS: null,
  LOAD_PROJECT_FAIL: null,

  LOAD_PROJECTS_BY_TECHNOLOGIES_SUCCESS: null,
  LOAD_PROJECTS_BY_TECHNOLOGIES_FAIL: null,

  LOAD_PROJECTS_BY_TYPE_SUCCESS: null,
  LOAD_PROJECTS_BY_TYPE_FAIL: null,

  LOAD_PROJECTS_BY_TYPE_AND_TECHNOLOGIES_SUCCESS: null,
  LOAD_PROJECTS_BY_TYPE_AND_TECHNOLOGIES_FAIL: null,

  LOAD_PROJECTS_BY_USER_SUCCESS: null,
  LOAD_PROJECTS_BY_USER_FAIL: null,

  POST_PROJECT_SUCCESS: null,
  POST_PROJECT_FAIL: null,

  FILTER: null,

  UPDATE_PAGINATION: null,

  CLEAR_PROJECT: null,
  CLEAR_PROJECTS_BY_TECHNOLOGY: null
});
